---
spring:
  application:
    name: "house-knx-automation"
house-knx-automation:
  printEvents: "${PRINT_EVENTS}"
  printControls: "${PRINT_CONTROLS}"
  knxGatewayAddress: "${KNX_GATEWAY_ADDRESS}"
  knxGatewayPort: "${KNX_GATEWAY_PORT}"
  timeZone: "${TIME_ZONE}"
  locationLat: "${LOCATION_LAT}"
  locationLon: "${LOCATION_LON}"
  morningTime: "${MORNING_TIME}"
  eveningTime: "${EVENING_TIME}"
  allJalousieControlGroupAddress: "${ALL_JALOUSIE_CONTROL_GROUP_ADDRESS}"
  allJalousieExceptBedroomsControlGroupAddress: "${ALL_JALOUSIE_EXCEPT_BEDROOMS_CONTROL_GROUP_ADDRESS}"
  dayNightModeControlGroupAddress: "${DAY_NIGHT_MODE_CONTROL_GROUP_ADDRESS}"
  heatingModeControlGroupAddress: "${HEATING_MODE_CONTROL_GROUP_ADDRESS}"
  sunriseEarliest: "${SUNRISE_EARLIEST}"
  sunriseLatest: "${SUNRISE_LATEST}"
  sunsetEarliest: "${SUNSET_EARLIEST}"
  sunsetLatest: "${SUNSET_LATEST}"
  offsetBeforeSunriseInSeconds: "${OFFSET_BEFORE_SUNRISE_IN_SECONDS}"
  offsetAfterSunriseInSeconds: "${OFFSET_AFTER_SUNRISE_IN_SECONDS}"
  offsetBeforeSunsetInSeconds: "${OFFSET_BEFORE_SUNSET_IN_SECONDS}"
  offsetAfterSunsetInSeconds: "${OFFSET_AFTER_SUNSET_IN_SECONDS}"
